### ISSUE TITLE
Live Rust: log show error  decode expected value

### ISSUE THREAD

**Issue by AlexiaChen** [nkaz001/hftbacktest#165]
First , Thank you this project 

## Environment

VM 

- 1 CPUs
- 1 GB

binancefutures toml

```toml
# Testnet: wss://fstream.binancefuture.com/ws
# Mainnet: wss://fstream.binance.com/ws
# Private: wss://fstream-auth.binance.com/ws
# Low-Latency Market Maker: wss://fstream-mm.binance.com/ws
stream_url = "wss://fstream.binance.com/ws"

# Testnet: https://testnet.binancefuture.com
# Mainnet: https://fapi.binance.com
# Low-Latency Market Maker: https://fapi-mm.binance.com
api_url = "https://fapi.binance.com"

order_prefix = "test"
api_key = "****"
secret = "****"
```

After I run connector and use live grid, the logs of strategy shows as follows, symbol: 1000shibusdt:

![image](https://github.com/user-attachments/assets/2ff7acd7-4aee-4bfd-87b4-5da1700bfbe0)

the  logs of connector, seems in ordermanager:

![image](https://github.com/user-attachments/assets/9ac4b8c1-df5b-4c60-961a-280f543cadb7)

I cannot see anything trade on Binance App

I searched the error text,  seems the logic run to here:

![image](https://github.com/user-attachments/assets/e4081c0e-6c06-4f88-8ee4-6253a1660edc)

and the root cause maybe in submit_order return error:

![image](https://github.com/user-attachments/assets/f2b54422-37bb-4d1e-8cec-95a7e930f3d9)
